/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWorkspaceRouteImport } from './routes/api/workspace'
import { Route as ApiWhatsappRouteImport } from './routes/api/whatsapp'
import { Route as ApiUsageRouteImport } from './routes/api/usage'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiTelegramRouteImport } from './routes/api/telegram'
import { Route as ApiSkillsRouteImport } from './routes/api/skills'
import { Route as ApiQueueRouteImport } from './routes/api/queue'
import { Route as ApiPairingRouteImport } from './routes/api/pairing'
import { Route as ApiModelsRouteImport } from './routes/api/models'
import { Route as ApiMemoryRouteImport } from './routes/api/memory'
import { Route as ApiLogsRouteImport } from './routes/api/logs'
import { Route as ApiKeysRouteImport } from './routes/api/keys'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiCronRouteImport } from './routes/api/cron'
import { Route as ApiConfigRouteImport } from './routes/api/config'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as AuthSignupRouteImport } from './routes/_auth.signup'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AppUsageRouteImport } from './routes/_app.usage'
import { Route as AppTradingRouteImport } from './routes/_app.trading'
import { Route as AppSocialRouteImport } from './routes/_app.social'
import { Route as AppSkillsRouteImport } from './routes/_app.skills'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSessionsRouteImport } from './routes/_app.sessions'
import { Route as AppOverviewRouteImport } from './routes/_app.overview'
import { Route as AppNodesRouteImport } from './routes/_app.nodes'
import { Route as AppLogsRouteImport } from './routes/_app.logs'
import { Route as AppGoogleRouteImport } from './routes/_app.google'
import { Route as AppDebugRouteImport } from './routes/_app.debug'
import { Route as AppCronRouteImport } from './routes/_app.cron'
import { Route as AppConfigRouteImport } from './routes/_app.config'
import { Route as AppCodingRouteImport } from './routes/_app.coding'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppChannelsRouteImport } from './routes/_app.channels'
import { Route as AppAgentsRouteImport } from './routes/_app.agents'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'
import { Route as ApiAuthRegisterRouteImport } from './routes/api/auth/register'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspaceRoute = ApiWorkspaceRouteImport.update({
  id: '/api/workspace',
  path: '/api/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappRoute = ApiWhatsappRouteImport.update({
  id: '/api/whatsapp',
  path: '/api/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsageRoute = ApiUsageRouteImport.update({
  id: '/api/usage',
  path: '/api/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramRoute = ApiTelegramRouteImport.update({
  id: '/api/telegram',
  path: '/api/telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSkillsRoute = ApiSkillsRouteImport.update({
  id: '/api/skills',
  path: '/api/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQueueRoute = ApiQueueRouteImport.update({
  id: '/api/queue',
  path: '/api/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPairingRoute = ApiPairingRouteImport.update({
  id: '/api/pairing',
  path: '/api/pairing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelsRoute = ApiModelsRouteImport.update({
  id: '/api/models',
  path: '/api/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemoryRoute = ApiMemoryRouteImport.update({
  id: '/api/memory',
  path: '/api/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLogsRoute = ApiLogsRouteImport.update({
  id: '/api/logs',
  path: '/api/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/api/keys',
  path: '/api/keys',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRoute = ApiCronRouteImport.update({
  id: '/api/cron',
  path: '/api/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfigRoute = ApiConfigRouteImport.update({
  id: '/api/config',
  path: '/api/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppUsageRoute = AppUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AppRoute,
} as any)
const AppTradingRoute = AppTradingRouteImport.update({
  id: '/trading',
  path: '/trading',
  getParentRoute: () => AppRoute,
} as any)
const AppSocialRoute = AppSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => AppRoute,
} as any)
const AppSkillsRoute = AppSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsRoute = AppSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AppRoute,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppNodesRoute = AppNodesRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsRoute = AppLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppRoute,
} as any)
const AppGoogleRoute = AppGoogleRouteImport.update({
  id: '/google',
  path: '/google',
  getParentRoute: () => AppRoute,
} as any)
const AppDebugRoute = AppDebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => AppRoute,
} as any)
const AppCronRoute = AppCronRouteImport.update({
  id: '/cron',
  path: '/cron',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigRoute = AppConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AppRoute,
} as any)
const AppCodingRoute = AppCodingRouteImport.update({
  id: '/coding',
  path: '/coding',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppChannelsRoute = AppChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRegisterRoute = ApiAuthRegisterRouteImport.update({
  id: '/api/auth/register',
  path: '/api/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/agents': typeof AppAgentsRoute
  '/channels': typeof AppChannelsRoute
  '/chat': typeof AppChatRoute
  '/coding': typeof AppCodingRoute
  '/config': typeof AppConfigRoute
  '/cron': typeof AppCronRoute
  '/debug': typeof AppDebugRoute
  '/google': typeof AppGoogleRoute
  '/logs': typeof AppLogsRoute
  '/nodes': typeof AppNodesRoute
  '/overview': typeof AppOverviewRoute
  '/sessions': typeof AppSessionsRoute
  '/settings': typeof AppSettingsRoute
  '/skills': typeof AppSkillsRoute
  '/social': typeof AppSocialRoute
  '/trading': typeof AppTradingRoute
  '/usage': typeof AppUsageRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/api/$': typeof ApiSplatRoute
  '/api/chat': typeof ApiChatRoute
  '/api/config': typeof ApiConfigRoute
  '/api/cron': typeof ApiCronRoute
  '/api/health': typeof ApiHealthRoute
  '/api/keys': typeof ApiKeysRoute
  '/api/logs': typeof ApiLogsRoute
  '/api/memory': typeof ApiMemoryRoute
  '/api/models': typeof ApiModelsRoute
  '/api/pairing': typeof ApiPairingRoute
  '/api/queue': typeof ApiQueueRoute
  '/api/skills': typeof ApiSkillsRoute
  '/api/telegram': typeof ApiTelegramRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/usage': typeof ApiUsageRoute
  '/api/whatsapp': typeof ApiWhatsappRoute
  '/api/workspace': typeof ApiWorkspaceRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/agents': typeof AppAgentsRoute
  '/channels': typeof AppChannelsRoute
  '/chat': typeof AppChatRoute
  '/coding': typeof AppCodingRoute
  '/config': typeof AppConfigRoute
  '/cron': typeof AppCronRoute
  '/debug': typeof AppDebugRoute
  '/google': typeof AppGoogleRoute
  '/logs': typeof AppLogsRoute
  '/nodes': typeof AppNodesRoute
  '/overview': typeof AppOverviewRoute
  '/sessions': typeof AppSessionsRoute
  '/settings': typeof AppSettingsRoute
  '/skills': typeof AppSkillsRoute
  '/social': typeof AppSocialRoute
  '/trading': typeof AppTradingRoute
  '/usage': typeof AppUsageRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/api/$': typeof ApiSplatRoute
  '/api/chat': typeof ApiChatRoute
  '/api/config': typeof ApiConfigRoute
  '/api/cron': typeof ApiCronRoute
  '/api/health': typeof ApiHealthRoute
  '/api/keys': typeof ApiKeysRoute
  '/api/logs': typeof ApiLogsRoute
  '/api/memory': typeof ApiMemoryRoute
  '/api/models': typeof ApiModelsRoute
  '/api/pairing': typeof ApiPairingRoute
  '/api/queue': typeof ApiQueueRoute
  '/api/skills': typeof ApiSkillsRoute
  '/api/telegram': typeof ApiTelegramRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/usage': typeof ApiUsageRoute
  '/api/whatsapp': typeof ApiWhatsappRoute
  '/api/workspace': typeof ApiWorkspaceRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/mcp': typeof McpRoute
  '/_app/agents': typeof AppAgentsRoute
  '/_app/channels': typeof AppChannelsRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/coding': typeof AppCodingRoute
  '/_app/config': typeof AppConfigRoute
  '/_app/cron': typeof AppCronRoute
  '/_app/debug': typeof AppDebugRoute
  '/_app/google': typeof AppGoogleRoute
  '/_app/logs': typeof AppLogsRoute
  '/_app/nodes': typeof AppNodesRoute
  '/_app/overview': typeof AppOverviewRoute
  '/_app/sessions': typeof AppSessionsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/skills': typeof AppSkillsRoute
  '/_app/social': typeof AppSocialRoute
  '/_app/trading': typeof AppTradingRoute
  '/_app/usage': typeof AppUsageRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/api/$': typeof ApiSplatRoute
  '/api/chat': typeof ApiChatRoute
  '/api/config': typeof ApiConfigRoute
  '/api/cron': typeof ApiCronRoute
  '/api/health': typeof ApiHealthRoute
  '/api/keys': typeof ApiKeysRoute
  '/api/logs': typeof ApiLogsRoute
  '/api/memory': typeof ApiMemoryRoute
  '/api/models': typeof ApiModelsRoute
  '/api/pairing': typeof ApiPairingRoute
  '/api/queue': typeof ApiQueueRoute
  '/api/skills': typeof ApiSkillsRoute
  '/api/telegram': typeof ApiTelegramRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/usage': typeof ApiUsageRoute
  '/api/whatsapp': typeof ApiWhatsappRoute
  '/api/workspace': typeof ApiWorkspaceRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mcp'
    | '/agents'
    | '/channels'
    | '/chat'
    | '/coding'
    | '/config'
    | '/cron'
    | '/debug'
    | '/google'
    | '/logs'
    | '/nodes'
    | '/overview'
    | '/sessions'
    | '/settings'
    | '/skills'
    | '/social'
    | '/trading'
    | '/usage'
    | '/login'
    | '/signup'
    | '/api/$'
    | '/api/chat'
    | '/api/config'
    | '/api/cron'
    | '/api/health'
    | '/api/keys'
    | '/api/logs'
    | '/api/memory'
    | '/api/models'
    | '/api/pairing'
    | '/api/queue'
    | '/api/skills'
    | '/api/telegram'
    | '/api/upload'
    | '/api/usage'
    | '/api/whatsapp'
    | '/api/workspace'
    | '/api/auth/$'
    | '/api/auth/register'
    | '/api/rpc/$'
    | '/api/trpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mcp'
    | '/agents'
    | '/channels'
    | '/chat'
    | '/coding'
    | '/config'
    | '/cron'
    | '/debug'
    | '/google'
    | '/logs'
    | '/nodes'
    | '/overview'
    | '/sessions'
    | '/settings'
    | '/skills'
    | '/social'
    | '/trading'
    | '/usage'
    | '/login'
    | '/signup'
    | '/api/$'
    | '/api/chat'
    | '/api/config'
    | '/api/cron'
    | '/api/health'
    | '/api/keys'
    | '/api/logs'
    | '/api/memory'
    | '/api/models'
    | '/api/pairing'
    | '/api/queue'
    | '/api/skills'
    | '/api/telegram'
    | '/api/upload'
    | '/api/usage'
    | '/api/whatsapp'
    | '/api/workspace'
    | '/api/auth/$'
    | '/api/auth/register'
    | '/api/rpc/$'
    | '/api/trpc/$'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/mcp'
    | '/_app/agents'
    | '/_app/channels'
    | '/_app/chat'
    | '/_app/coding'
    | '/_app/config'
    | '/_app/cron'
    | '/_app/debug'
    | '/_app/google'
    | '/_app/logs'
    | '/_app/nodes'
    | '/_app/overview'
    | '/_app/sessions'
    | '/_app/settings'
    | '/_app/skills'
    | '/_app/social'
    | '/_app/trading'
    | '/_app/usage'
    | '/_auth/login'
    | '/_auth/signup'
    | '/api/$'
    | '/api/chat'
    | '/api/config'
    | '/api/cron'
    | '/api/health'
    | '/api/keys'
    | '/api/logs'
    | '/api/memory'
    | '/api/models'
    | '/api/pairing'
    | '/api/queue'
    | '/api/skills'
    | '/api/telegram'
    | '/api/upload'
    | '/api/usage'
    | '/api/whatsapp'
    | '/api/workspace'
    | '/api/auth/$'
    | '/api/auth/register'
    | '/api/rpc/$'
    | '/api/trpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  McpRoute: typeof McpRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiConfigRoute: typeof ApiConfigRoute
  ApiCronRoute: typeof ApiCronRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiKeysRoute: typeof ApiKeysRoute
  ApiLogsRoute: typeof ApiLogsRoute
  ApiMemoryRoute: typeof ApiMemoryRoute
  ApiModelsRoute: typeof ApiModelsRoute
  ApiPairingRoute: typeof ApiPairingRoute
  ApiQueueRoute: typeof ApiQueueRoute
  ApiSkillsRoute: typeof ApiSkillsRoute
  ApiTelegramRoute: typeof ApiTelegramRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ApiUsageRoute: typeof ApiUsageRoute
  ApiWhatsappRoute: typeof ApiWhatsappRoute
  ApiWorkspaceRoute: typeof ApiWorkspaceRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspace': {
      id: '/api/workspace'
      path: '/api/workspace'
      fullPath: '/api/workspace'
      preLoaderRoute: typeof ApiWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp': {
      id: '/api/whatsapp'
      path: '/api/whatsapp'
      fullPath: '/api/whatsapp'
      preLoaderRoute: typeof ApiWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/usage': {
      id: '/api/usage'
      path: '/api/usage'
      fullPath: '/api/usage'
      preLoaderRoute: typeof ApiUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram': {
      id: '/api/telegram'
      path: '/api/telegram'
      fullPath: '/api/telegram'
      preLoaderRoute: typeof ApiTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/skills': {
      id: '/api/skills'
      path: '/api/skills'
      fullPath: '/api/skills'
      preLoaderRoute: typeof ApiSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/queue': {
      id: '/api/queue'
      path: '/api/queue'
      fullPath: '/api/queue'
      preLoaderRoute: typeof ApiQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pairing': {
      id: '/api/pairing'
      path: '/api/pairing'
      fullPath: '/api/pairing'
      preLoaderRoute: typeof ApiPairingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/models': {
      id: '/api/models'
      path: '/api/models'
      fullPath: '/api/models'
      preLoaderRoute: typeof ApiModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memory': {
      id: '/api/memory'
      path: '/api/memory'
      fullPath: '/api/memory'
      preLoaderRoute: typeof ApiMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/logs': {
      id: '/api/logs'
      path: '/api/logs'
      fullPath: '/api/logs'
      preLoaderRoute: typeof ApiLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keys': {
      id: '/api/keys'
      path: '/api/keys'
      fullPath: '/api/keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron': {
      id: '/api/cron'
      path: '/api/cron'
      fullPath: '/api/cron'
      preLoaderRoute: typeof ApiCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/config': {
      id: '/api/config'
      path: '/api/config'
      fullPath: '/api/config'
      preLoaderRoute: typeof ApiConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/usage': {
      id: '/_app/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof AppUsageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trading': {
      id: '/_app/trading'
      path: '/trading'
      fullPath: '/trading'
      preLoaderRoute: typeof AppTradingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/social': {
      id: '/_app/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof AppSocialRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/skills': {
      id: '/_app/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AppSkillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions': {
      id: '/_app/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AppSessionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/overview': {
      id: '/_app/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nodes': {
      id: '/_app/nodes'
      path: '/nodes'
      fullPath: '/nodes'
      preLoaderRoute: typeof AppNodesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logs': {
      id: '/_app/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AppLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/google': {
      id: '/_app/google'
      path: '/google'
      fullPath: '/google'
      preLoaderRoute: typeof AppGoogleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/debug': {
      id: '/_app/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof AppDebugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cron': {
      id: '/_app/cron'
      path: '/cron'
      fullPath: '/cron'
      preLoaderRoute: typeof AppCronRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/config': {
      id: '/_app/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof AppConfigRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/coding': {
      id: '/_app/coding'
      path: '/coding'
      fullPath: '/coding'
      preLoaderRoute: typeof AppCodingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/channels': {
      id: '/_app/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof AppChannelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents': {
      id: '/_app/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AppAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/api/auth/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAgentsRoute: typeof AppAgentsRoute
  AppChannelsRoute: typeof AppChannelsRoute
  AppChatRoute: typeof AppChatRoute
  AppCodingRoute: typeof AppCodingRoute
  AppConfigRoute: typeof AppConfigRoute
  AppCronRoute: typeof AppCronRoute
  AppDebugRoute: typeof AppDebugRoute
  AppGoogleRoute: typeof AppGoogleRoute
  AppLogsRoute: typeof AppLogsRoute
  AppNodesRoute: typeof AppNodesRoute
  AppOverviewRoute: typeof AppOverviewRoute
  AppSessionsRoute: typeof AppSessionsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSkillsRoute: typeof AppSkillsRoute
  AppSocialRoute: typeof AppSocialRoute
  AppTradingRoute: typeof AppTradingRoute
  AppUsageRoute: typeof AppUsageRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentsRoute: AppAgentsRoute,
  AppChannelsRoute: AppChannelsRoute,
  AppChatRoute: AppChatRoute,
  AppCodingRoute: AppCodingRoute,
  AppConfigRoute: AppConfigRoute,
  AppCronRoute: AppCronRoute,
  AppDebugRoute: AppDebugRoute,
  AppGoogleRoute: AppGoogleRoute,
  AppLogsRoute: AppLogsRoute,
  AppNodesRoute: AppNodesRoute,
  AppOverviewRoute: AppOverviewRoute,
  AppSessionsRoute: AppSessionsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSkillsRoute: AppSkillsRoute,
  AppSocialRoute: AppSocialRoute,
  AppTradingRoute: AppTradingRoute,
  AppUsageRoute: AppUsageRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  McpRoute: McpRoute,
  ApiSplatRoute: ApiSplatRoute,
  ApiChatRoute: ApiChatRoute,
  ApiConfigRoute: ApiConfigRoute,
  ApiCronRoute: ApiCronRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiKeysRoute: ApiKeysRoute,
  ApiLogsRoute: ApiLogsRoute,
  ApiMemoryRoute: ApiMemoryRoute,
  ApiModelsRoute: ApiModelsRoute,
  ApiPairingRoute: ApiPairingRoute,
  ApiQueueRoute: ApiQueueRoute,
  ApiSkillsRoute: ApiSkillsRoute,
  ApiTelegramRoute: ApiTelegramRoute,
  ApiUploadRoute: ApiUploadRoute,
  ApiUsageRoute: ApiUsageRoute,
  ApiWhatsappRoute: ApiWhatsappRoute,
  ApiWorkspaceRoute: ApiWorkspaceRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAuthRegisterRoute: ApiAuthRegisterRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
